<?php
require('AppModel.php');

class FakeData extends AppModel
{
	public $generated_names = [];
	public $total_array_names;

	function __construct(){
		set_time_limit(0);
		$conn = mysql_connect('mysql.bbgl.kinghost.net', 'bbgl', '5JmzuRr7LMT4') or die (mysql_error()); 
		mysql_set_charset('utf8', $conn);
		mysql_select_db('bbgl', $conn) or die (mysql_error());
		$this->total_array_names = count($this->names) - 1;
	}

	public function generateFakeProfiles($total, $restart = false){

		if ($restart) {
			$this->resetTables();
		}
		for ($i = 0; $i < $total; $i++) {
			do {
				$full_name = $this->getFullName();
				$transaction_complete = true;

				$username = self::generateUsername($full_name);
				$birth_date = rand(DATE('Y') - 60, DATE('Y') - 18) . '-01-01';

				$query = "".
					"INSERT INTO accounts 
						(username, password, created)
					VALUES ('{$username}', '123mudar', CURRENT_TIMESTAMP)";
				if (mysql_query($query) or die ('Erro ao salvar a conta: ' . mysql_error())) { // Insert on account table
					// if account was correctly inserted, insert profile
					$account_id = mysql_insert_id();
					$query = "".
						"INSERT INTO profiles 
							(name, birth_date, images_folder, account_id, created)
						VALUES ('{$full_name}', '{$birth_date}', 'dda98s7da89.jpg', {$account_id}, CURRENT_TIMESTAMP)";

					if (!mysql_query($query)) { // Insert profile from accuont
						$delete = "DELETE FROM accounts WHERE id = {$account_id}";
						$transaction_complete = false;
					}
				} else {
					!$transaction_complete = false;
				}
			} while (!$transaction_complete);
		}
	}
	static function removeAcentos($string){
		return preg_replace('/[`^~\'"]/', null, iconv( 'UTF-8', 'ASCII//TRANSLIT', $string));
	}
	public function generateUsername($username){
		$username = str_replace(' ', '', $username);
		$username = $this->removeAcentos($username);
		$username = strtolower($username);
		return "{$username}@gmail.com";
	}
	public function resetTables(){
		mysql_query('DELETE FROM images') or die('On delete table images: ' . mysql_error());
		mysql_query('DELETE FROM messages') or die('On delete table messages: ' . mysql_error());
		mysql_query('DELETE FROM relationships') or die('On delete table relationships: ' . mysql_error());
		mysql_query('DELETE FROM profiles') or die('On delete table profiles: ' . mysql_error());
		mysql_query('DELETE FROM accounts') or die('On delete table accounts: ' . mysql_error());

		mysql_query('ALTER TABLE images AUTO_INCREMENT = 1') or die('On alter table images: ' . mysql_error());
		mysql_query('ALTER TABLE messages AUTO_INCREMENT = 1') or die('On alter table messages: ' . mysql_error());
		mysql_query('ALTER TABLE relationships AUTO_INCREMENT = 1') or die('On alter table relationships: ' . mysql_error());
		mysql_query('ALTER TABLE profiles AUTO_INCREMENT = 1') or die('On alter table profiles: ' . mysql_error());
		mysql_query('ALTER TABLE accounts AUTO_INCREMENT = 1') or die('On alter table accounts: ' . mysql_error());
	}
	public function getFullName(){
		$name = $this->names[rand(0, $this->total_array_names)];
		$last_name = $this->names[rand(0, $this->total_array_names)];
		
		while ($name == $last_name) {
			$last_name = $this->names[rand(0, $this->total_array_names)];
		}

		return "{$name} {$last_name}";
	}

	public $names = [
			'Aarão',
			'Abel',
			'Abílio',
			'Abraão',
			'Acácio',
			'Acúrcio',
			'Adalberto',
			'Adão',
			'Adauto',
			'Adelino',
			'Adelmiro',
			'Ademar',
			'Ademir',
			'Adérito',
			'Ado',
			'Adolfo',
			'Adosindo',
			'Adriano',
			'Adrião',
			'Aécio',
			'Afonso',
			'Agostinho',
			'Aguinaldo',
			'Alan',
			'Albano',
			'Alberto',
			'Albino',
			'Aldino',
			'Alexander',
			'Alexandre',
			'Alfeu',
			'Alfredo',
			'Alírio',
			'Altair',
			'Altino',
			'Álvaro',
			'Amadeu',
			'Amado',
			'Amador',
			'Amândio',
			'Amaro',
			'Amável',
			'Américo',
			'Amilcar',
			'Anacleto',
			'Anastácio',
			'Anderson',
			'André',
			'Ângelo',
			'Aníbal',
			'Anselmo',
			'Antenor',
			'Antero',
			'António',
			'Apolinário',
			'Apólo',
			'Aponino',
			'Aquiles',
			'Arcelino',
			'Argeu',
			'Ari',
			'Arlindo',
			'Armando',
			'Arménio',
			'Armindo',
			'Arnaldo',
			'Artur',
			'Asdrúbal',
			'Atanásio',
			'Atílio',
			'Augusto',
			'Aurélio',
			'Avelino',
			'Baltasar',
			'Barnabé',
			'Bartolomeu',
			'Basílio',
			'Belarmino',
			'Belmiro',
			'Benedito',
			'Benito',
			'Benjamim',
			'Bernardo',
			'Bonifácio',
			'Brandon',
			'Bráulio',
			'Brígido',
			'Bruno',
			'Bryan',
			'Caetano',
			'Caio',
			'Calebe',
			'Calisto',
			'Calvin',
			'Calvino',
			'Camilo',
			'Cândido',
			'Capitolino',
			'Carlos',
			'Cássio',
			'Celso',
			'César',
			'Cesário',
			'Cícero',
			'Ciro',
			'Claudino',
			'Cláudio',
			'Cléber',
			'Clemente',
			'Clementino',
			'Clodoaldo',
			'Clóvis',
			'Constantino',
			'Consuelo',
			'Cornélio',
			'Cosme',
			'Cristiano',
			'Cristóvão',
			'Custódio',
			'Meninos',
			'Edelmiro',
			'Edgar',
			'Ediberto',
			'Edmar',
			'Edmundo',
			'Edson',
			'Eduardo',
			'Egídio',
			'Eleutério',
			'Eli',
			'Elias',
			'Élio',
			'Elizeu',
			'Elói',
			'Elton',
			'Elvis',
			'Emanuel',
			'Emídio',
			'Emílio',
			'Énio',
			'Erasmo',
			'Erico',
			'Ermínio',
			'Ernane',
			'Ernesto',
			'Esaú',
			'Esdras',
			'Estevão',
			'Eugénio',
			'Eurico',
			'Eusébio',
			'Eutímio',
			'Evaldo',
			'Evandro',
			'Ezequias',
			'Ezequiel',
			'Fabiano',
			'Fábio',
			'Fabrício',
			'Faustino',
			'Fausto',
			'Felipe/Filipe',
			'Felisberto',
			'Félix',
			'Ferdinando',
			'Fernando',
			'Firmino',
			'Flaviano',
			'Flávio',
			'Florêncio',
			'Florival',
			'Francisco',
			'Franklin',
			'Frederico',
			'Gabriel',
			'Gaspar',
			'Gastão',
			'George',
			'George',
			'Geraldino',
			'Geraldo',
			'Gerson',
			'Gervásio',
			'Getúlio',
			'Gideão',
			'Gil',
			'Gilberto',
			'Gildo',
			'Godofredo',
			'Golias',
			'Gonçalo',
			'Gregório',
			'Guido',
			'Guilherme',
			'Gustavo',
			'Hamilton',
			'Heitor',
			'Hélder',
			'Hélio',
			'Henrique',
			'Herculano',
			'Hércules',
			'Hermes',
			'Hernâni',
			'Herodes',
			'Hilário',
			'Hildefonso',
			'Hilton',
			'Hipólito',
			'Honório',
			'Horácio',
			'Hugo',
			'Humberto',
			'Idalécio',
			'Igor',
			'Ilídio',
			'Inácio',
			'Isaías',
			'Ismael',
			'Israel',
			'Ivan',
			'Ivo',
			'Jacinto',
			'Jaime',
			'Januário',
			'Jeremias',
			'Jerônimo',
			'Jesus',
			'Jó',
			'João',
			'Joaquim',
			'Joel',
			'Jonas',
			'Jonathan',
			'Jorge',
			'Josafá',
			'José',
			'Josué',
			'Joviano',
			'Juliano',
			'Júlio',
			'Justino',
			'Ladislau',
			'Lancelote',
			'Lauro',
			'Leandro',
			'Leocádio',
			'Leonardo',
			'Leôncio',
			'Leonel',
			'Leónidas',
			'Leopoldo',
			'Levi',
			'Libânio',
			'Licínio',
			'Lino',
			'Lisandro',
			'Lívio',
			'Lourenço',
			'Lourival',
			'Lucas',
			'Luciano',
			'Lúcio',
			'Ludovico',
			'Luis',
			'Manuel',
			'Marcelo',
			'Márcio',
			'Marco',
			'Marcos',
			'Mário',
			'Martim',
			'Martinho',
			'Mateus',
			'Maurício',
			'Mauro',
			'Maximiliano',
			'Máximo',
			'Michael',
			'Miguel',
			'Milton',
			'Moacir',
			'Moisés',
			'Muriel',
			'Nabal',
			'Nadir',
			'Narciso',
			'Natálio',
			'Natanael',
			'Naum',
			'Nazário',
			'Nélson',
			'Nero',
			'Nestor',
			'Nicolas',
			'Nicolau',
			'Nilson',
			'Nilton',
			'Nivaldo',
			'Norberto',
			'Normando',
			'Nuno',
			'Octávio',
			'Odair',
			'Olavo',
			'Olegário',
			'Olímpio',
			'Olivier',
			'Olívio',
			'Omar',
			'Orfeu',
			'Orlando',
			'Óscar',
			'Osmar',
			'Osvaldo',
			'Otoniel',
			'Pablo',
			'Pascoal',
			'Patrício',
			'Paulino',
			'Paulo',
			'Pedro',
			'Pelágio',
			'Perceu',
			'Péricles',
			'Plácido',
			'Priscilo',
			'Rafael',
			'Raimundo',
			'Ramiro',
			'Ramom',
			'Raul',
			'Reginaldo',
			'Reinaldo',
			'Renan',
			'Renato',
			'Ricardino',
			'Ricardo',
			'Roberto',
			'Rodrigo',
			'Rogério',
			'Romeu',
			'Romualdo',
			'Rômulo',
			'Ronaldo',
			'Rúben',
			'Rodolfo',
			'Rui',
			'Sabino',
			'Salomão',
			'Salvador',
			'Samuel',
			'Sandro',
			'Saúl',
			'Sebastião',
			'Serafim',
			'Sérgio',
			'Sidney',
			'Sidónio',
			'Silvano',
			'Silvestre',
			'Silvino',
			'Sílvio',
			'Simão',
			'Tadeu',
			'Tarcísio',
			'Telmo',
			'Teófilo',
			'Theo',
			'Tiago',
			'Tibúrcio',
			'Timóteo',
			'Tito',
			'Tomás',
			'Tomé',
			'Tristão',
			'Túlio',
			'Vágner',
			'Valadares',
			'Valdemar',
			'Valdemiro',
			'Valdir',
			'Valdo',
			'Valentim',
			'Valentino',
			'Valério',
			'Valter',
			'Vasco',
			'Veloso',
			'Venâncio',
			'Venceslau',
			'Vicente',
			'Victor',
			'Vidigal',
			'Vieira',
			'Vilela',
			'Vilmar',
			'Vinicios',
			'Virgílio',
			'Virgolino',
			'Viriato',
			'Vital',
			'Vitorino',
			'Volne',
			'Gleyson'
		];
}
?>